# Generated by Django 6.0 on 2025-12-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todos_options_todos_put_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='todos',
            name='title',
            field=models.CharField(default='nothing', max_length=100, null=True),
        ),
    ]
